### ISSUE TITLE
회원가입, 로그인 구현 완료시 로그인 상태의 메인페이지 구현

### ISSUE THREAD

**Issue by merrybmc** [H99-9-A-1Team-Project/Front-End#61]
회원가입, 로그인 구현 완료시 로그인 상태의 메인페이지 구현

_Originally posted by @merrybmc in https://github.com/H99-9-A-1Team-Project/Front-End/issues/60#issuecomment-1313096162_

**Comment by merrybmc** [comment]
우선 상담신청 페이지 작업

**Comment by ksu930** [comment]
메인페이지 구현 완료
